Inscription2
WildCodeSchool-2023-09/php-p2-strascook pull request #33
Opened 2023-11-19 19:26 UTC by LauraW-code

Ajout des champs manquant et insertion en BDD du formulaire inscription+sécurisation

2023-11-19 19:50 UTC, Stephdu33 approved these changes

2023-11-19 20:04 UTC, vincentr-wcs requested changes

2023-11-19 20:04 UTC, vincentr-wcs commented on src/Controller/InscriptionController.php
> +                $errors['password'] = 'Veuillez renseigner le nom';
C'est toujours nom dans tes messages ?

2023-11-19 20:13 UTC, LauraW-code commented on src/Controller/InscriptionController.php
> +                $errors['password'] = 'Veuillez renseigner le nom';
Ah nom nom xD la fatigue, je corrige de suite

2023-11-20 15:45 UTC, Maximecb83 approved these changes

2023-11-20 17:22 UTC, vincentr-wcs approved these changes

2023-11-20 17:22 UTC, merged