1ere version de la navbar avec routing
WildCodeSchool-2023-09/php-p2-strascook pull request #4
Opened 2023-11-08 15:58 UTC by lderi78

2023-11-08 16:05 UTC, Maximecb83 approved these changes

2023-11-08 16:16 UTC, LauraW-code requested changes
Je pense que pour les routes il vaut mieux n'utiliser qu'une seule et même méthode pour afficher les pages, type 'index', ce sera plus pertinent qu'avoir une méthode 'réservation' pour la page réservation, 'contact' pour la page contact etc...
Si tu peux faire cette modif, le reste me paraît nickel!

2023-11-08 22:23 UTC, lderi78 commented
> Je pense que pour les routes il vaut mieux n'utiliser qu'une seule et même méthode pour afficher les pages, type 'index', ce sera plus pertinent qu'avoir une méthode 'réservation' pour la page réservation, 'contact' pour la page contact etc... Si tu peux faire cette modif, le reste me paraît nickel!

Tu veux que les méthodes des 6 classes que j'ai créées soient renommées en "index" ? 
Afin de satisfaire ma curiosité ça servirait à quoi vu qu'on ne devrait pas toucher à ces classes ? 
Je me souviens que Vincent nous avait montré de la façon dont tu parles mais Yavuz lors de la présentation du Mini MVC m'avait montré comme j'ai fait. C'est qui le patron ? :D :D :dagger: 

Bon c'était histoire de laisser un message sur github, mais je suis intéressé par la réponse.

2023-11-09 08:04 UTC, LauraW-code approved these changes

2023-11-09 09:27 UTC, vincentr-wcs requested changes
Deux trois choses à modifier mais sinon c'est très bien !

2023-11-09 09:27 UTC, vincentr-wcs commented on src/View/Home/index.html.twig
> +    <p>Je vous propose de copier à la fin du projet le contenu de la page accueil ici<p>
Mauvaise idée haha vous pouvez le garder soit en le déplaçant la logique dans une autre page ou en le laissant mais n'attendez pas le dernier moment pour faire la page d'accueil surtout si dans votre backlog elle doit être fait avant la dernière semaine

2023-11-09 09:27 UTC, vincentr-wcs commented on src/View/accueil/accueil.html.twig
> +C'est ici que va le code de la page Accueil.
Ici vaudrait mieux mettre en commentaire quand on veut laisser des indications ou explications code

2023-11-09 09:27 UTC, vincentr-wcs commented on src/View/connexion/connexion.html.twig
> +C'est ici que va le code de la page Connexion.
idem

2023-11-09 09:27 UTC, vincentr-wcs commented on src/View/contact/contact.html.twig
> +C'est ici que va le code de la page Contact.
idem

2023-11-09 09:27 UTC, vincentr-wcs commented on src/View/inscription/inscription.html.twig
> +C'est ici que va le code de la page Inscription.
idem

2023-11-09 09:27 UTC, vincentr-wcs commented on public/js/script.js
Pourquoi y'a un fichier vide ? Si c'est vide il faut l'enlever de la PR. Et on crée le fichier quand on a besoin pour la userstories

2023-11-09 09:27 UTC, vincentr-wcs commented on src/View/layout.html.twig
> +        <script src="/js/script.js" ></script>
Le fichier est vide donc faut enlever cette ligne

2023-11-09 09:27 UTC, vincentr-wcs commented on src/View/menus/menus.html.twig
> +C'est ici que va le code de la page Menus.
idem plutôt en commentaire

2023-11-09 09:27 UTC, vincentr-wcs commented on src/View/reservation/reservation.html.twig
> +C'est ici que va le code de la page Reservation.
idem plutôt en commentaire

2023-11-09 09:39 UTC, lderi78 commented on src/View/layout.html.twig
> +        <script src="/js/script.js" ></script>
Car je suis prévoyant. Yavuz nous a expliqué qu'il fallait tout prévoir à l'avance sinon ça porte un nom... je ne me souviens plus du nom. Mais ça a été notifié à la team du projet et ils étaient pas contre. Hé oui, il se peut que je mette du javascript (comme je l'ai fait dans mon premier projet [ouverture d'un canvas] ) :-)

2023-11-09 09:42 UTC, lderi78 commented on src/View/Home/index.html.twig
> +    <p>Je vous propose de copier à la fin du projet le contenu de la page accueil ici<p>
On ne va pas attendre le dernier moment pour faire la page d'accueil, on va juste faire un copié/collé une fois qu'elle sera terminée. Quand on est débutant (comme moi) on ne préfère pas retirer quelque chose du code original (du MVC). Vu que c'est le squelette du site, il faut que ceux qui travaillent dessus puisse retrouver ce qu'ils ont vu durant les cours. Je l'ai expliqué à la team avant le PR, la Team était d'accord.

2023-11-09 09:45 UTC, lderi78 commented on src/View/accueil/accueil.html.twig
> +C'est ici que va le code de la page Accueil.
Je ne suis pas d'accord:  c'est plus visuel pour des débutants. Le texte affiché on peut le retrouver dans le code et indique le bon fonctionnement du squelette. Libre a celui qui va implémenter son code de le retirer ou le passer en commentaire.

2023-11-09 09:49 UTC, vincentr-wcs commented on src/View/Home/index.html.twig
> +    <p>Je vous propose de copier à la fin du projet le contenu de la page accueil ici<p>
D'acc

2023-11-09 09:49 UTC, vincentr-wcs commented on src/View/accueil/accueil.html.twig
> +C'est ici que va le code de la page Accueil.
Non on ne laisse pas dans un fichier du texte brut qui indique des consignes ou autres. C'est pour ça qu'on a inventé les commentaires donc faut les utiliser ;)

2023-11-09 09:50 UTC, vincentr-wcs commented on src/View/layout.html.twig
> +        <script src="/js/script.js" ></script>
D'acc

2023-11-09 10:20 UTC, lderi78 commented on src/View/accueil/accueil.html.twig
> +C'est ici que va le code de la page Accueil.
Pourquoi vous nous avez fourni le mini MVC avec la page "Hello Wilders" et ne pas l'avoir mis en commentaire dans ce cas ?

2023-11-09 10:22 UTC, vincentr-wcs commented on src/View/accueil/accueil.html.twig
> +C'est ici que va le code de la page Accueil.
Parce que c'est du code et pas un commentaire ;)

2023-11-10 08:43 UTC, vincentr-wcs commented
Conflit à régler :)

2023-11-14 10:48 UTC, yavuzkutuk approved these changes

2023-11-14 10:50 UTC, yavuzkutuk approved these changes

2023-11-14 10:51 UTC, yavuzkutuk approved these changes

2023-11-14 10:53 UTC, yavuzkutuk approved these changes

2023-11-14 13:22 UTC, vincentr-wcs approved these changes
Bien joué !

2023-11-14 13:22 UTC, merged