footer v1
WildCodeSchool-2023-09/php-p2-strascook pull request #5
Opened 2023-11-08 16:02 UTC by Maximecb83

2023-11-08 16:20 UTC, LauraW-code requested changes
La version que tu as push n'a pas les routes modifiées avec la méthode index, attention aussi je crois que ton include du footer sur ton fichier layout.html.twig doit se faire avant les éventuels script JS (à vérifier, mais il me semble que les scripts c'est vraiment tout à la fin)

2023-11-09 09:22 UTC, Stephdu33 approved these changes

2023-11-10 08:51 UTC, vincentr-wcs commented
Tu as des conflits @Maximecb83 :)

2023-11-10 08:55 UTC, LauraW-code approved these changes
Les conflits sont réglés super!

2023-11-10 11:38 UTC, vincentr-wcs approved these changes
Bien joué

2023-11-10 11:39 UTC, merged